[package]
name = "jvob"
version = "0.1.0"
edition = "2024"
authors = ["me <dimoiko100@gmail.com>"]

[lib]
name = "jvob"
path = "src/lib.rs"

[dependencies]
json-syntax = "0.12.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
